### ISSUE TITLE
Error when disabling pagination 

### ISSUE THREAD

**Issue by dannygunawan** [nacasha/CIgniter-Datatables#10]
Setting
`->set_options('paging',"false")`

will cause SQL error due to LIMIT -1 keyword in the generated query.

Adding simple checking to variable length value in DatatablesBuilder.php will fix the error
```
if ($length!=-1) {
    $this->_db->limit($length, $start);
}
```

**Comment by nacasha** [comment]
Fixed 870b1caadbf9a2756b513c1e58fe5f153086b399
