### ISSUE TITLE
bug tablename "AS"

### ISSUE THREAD

**Issue by plonknimbuzz** [nacasha/CIgniter-Datatables#3]
hi bro,
thanks for this awesome works.

i used this repo twice, and i remember if this repo have bug.

if we have tablename which contains "as" the tablename will truncated
example:
nama_asli => become: nama_
tbl_xxxxasyyyyy =>become: tbl_xxxx

https://github.com/nacasha/CIgniter-Datatables/blob/0fdcf6f49bd8d81733e0bef7d5023d98fa550976/libraries/Datatables.php#L228

**Comment by nacasha** [comment]
Hi, thanks for open this issue :)
I will fix it as soon as possible

**Comment by nacasha** [comment]
Fixed on 261f83c

**Comment by plonknimbuzz** [comment]
@nacasha thanks for this awesome library
