### ISSUE TITLE
How to show multiple tables in 1 page

### ISSUE THREAD

**Issue by plonknimbuzz** [nacasha/CIgniter-Datatables#4]
Hi nacasha.
is possible to use this library to build multiple table in 1 page?
because i always use iframe to hotfix (shortcut) this issue.

thanks for advanced.

**Comment by nacasha** [comment]
Sorry for being late to reply
i will add the feature as soon as possible, thanks for you suggestion

**Comment by plonknimbuzz** [comment]
nah, just do that if you have free time only. i still can use manual script for another table.
anyway this library really help me alot. i never think that create datatables with CI will be so easier.
great job @nacasha

**Comment by nacasha** [comment]
added 1631892

**Comment by plonknimbuzz** [comment]
omg, you already do that. Great job man. i hope this repo will significant increase your CV
