### ISSUE TITLE
The way to add pagination in both [top and down]

### ISSUE THREAD

**Issue by satrianivzla** [nacasha/CIgniter-Datatables#7]
Hi there
This is not a issue as well, is just a comment for cases that you want to have pagination in top and down, go to DatatablesBuilder.php and  search  line  176  where start $output and add this lines 		        	

                               \"pagingType\": \"full_numbers\",
		        	\"sDom\": '<\"top\"lfprtip><\"bottom\"><\"clear\">',

**Comment by nacasha** [comment]
Thank you for your contribution, I am going to add this to the documentation

**Comment by satrianivzla** [comment]
You're welcome!

**Comment by nacasha** [comment]
resolved a83eeab
